languaje: node_js
node_js:
  - node #latest stable Node.js release 

stages:
  - build
  - name: githubDeploy
    if: tag IS present

jobs:
  include:
    - stage: build
      name: "Build css"
      script:
        - npm install
        - npm run gulp build
    - stage: githubDeploy
      provider: npm
      name: "Deploy to npm"
      email: "$npm_email"
      api_key: "$npm_token"
      skip_cleanup: true
      