languaje: node_js
node_js:
  - node #latest stable Node.js release 

stages:
  - build
  - name: githubDeploy
    if: tag IS present

jobs:
  include:
    - stage: build
      name: "Build css"
      script:
        - npm install
        - npm run gulp build
    - stage: githubDeploy
      name: "Deploy to Github"
      provider: releases      
      api_key: "$github_release"
      file: 
        - "css/*"
        - "javascript/*"
      skip_cleanup: true