languaje: node_js
node_js:
  - node #latest stable Node.js release 

cache:
  directories:
    - "node_modules"

install:
  - npm install

script:
  - npm run gulp build

after_success:
  - ./predeploy.sh

deploy:
  - provider: npm
    name: "$TRAVIS_TAG"
    email: "$npm_email"
    api_key: "$npm_token"
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    name: "$TRAVIS_TAG"
    api_key: "$github_release"
    file: 
      - css/skeleton-styled.min.css
      - css/skeleton-styled.css
      - javascript/skeleton-styled.js
      - javascript/skeleton-styled.min.js
    skip_cleanup: true
    on:
      tags: true