languaje: node_js
node_js:
  - "node" #latest stable Node.js release 

jobs:
  include:
    - stage: build
      name: "Build css"
      script:
        - npm install
        - npm run gulp build

deploy:  
  - provider: npm
  email: "$npm_email"
  api_key: "$npm_token"  
  - provider: releases
  api_key: "$github_release"
  file: 
    - "css/*"
  skip_cleanup: true
  on:
    tags: true
