languaje: node_js
node_js:
  - "node" #latest stable Node.js release 

cache:
  directories:
    - "node_modules"

install:
  - npm install

script:
  - npm run gulp build

before_deploy:
  - npm config set git-tag-version false
  - npm version $TRAVIS_TAG
  - npm version
  - git commit --amend -a -m "Change npm version"

after_deploy:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git push --force origin master

deploy:
  - provider: npm
    name: "$TRAVIS_TAG"
    email: "$npm_email"
    api_key: "$npm_token"
    on:
      tags: true
  - provider: releases
    name: "$TRAVIS_TAG"
    api_key: "$github_release"
    file: 
      - "css/*"
      - "javascript/*"
    skip_cleanup: true
    on:
      tags: true