languaje: node_js
node_js:
  - node #latest stable Node.js release 

cache:
  directories:
    - "node_modules"

install:
  - npm install

script:
  - npm run gulp build

deploy:
  - provider: npm
    name: "$TRAVIS_TAG"
    email: "$npm_email"
    api_key: "$npm_token"
    skip_cleanup: true
    on:
      tags: true