languaje: node_js
node_js:
  - "node" #latest stable Node.js release 

cache:
  directories:
    - "node_modules"

install:
  - npm install

script:
  - npm run gulp build

deploy:
  provider: npm
  name: "Deploy to npm"
  email: "$npm_email"
  api_key: "$npm_token"
  on:
    tags: true
    
deploy:
  provider: releases
  name: "Deploy to github releases"
  api_key: "$github_release"
  file: "css/*"
  skip_cleanup: true
  on:
    tags: true